/**
 * Offline Storage — CRUD for offline data packages.
 *
 * Each package is a self-contained snapshot of all API data needed for
 * document generation without a live Tacton connection.
 *
 * Storage: IndexedDB via Dexie (offlinePackages table, added in schema v4).
 * Export:  JSON file download for sharing.
 * Import:  Parse JSON → insert into DB.
 */

import Dexie from 'dexie';

// ─── Access the shared DB instance ──────────────────────────────────────

const db = new Dexie('TactonDocGen');
// Re-declare latest schema so Dexie opens correctly from this module
db.version(4).stores({
  instances:       '++id, name, url',
  tokens:          'key',
  projects:        'id, documentId, instanceId, updatedAt',
  tickets:         '[projectId+ticketId], projectId',
  variables:       '++id, projectId, name, type, order, sectionId, catalogueId',
  settings:        'key',
  catalogues:      '++id, projectId, scope, name, order',
  sections:        '++id, catalogueId, projectId, name, order',
  offlinePackages: '++id, name, instanceUrl, ticketId, capturedAt',
});

// ─── Package shape ──────────────────────────────────────────────────────

/**
 * @typedef {Object} OfflinePackage
 * @property {number}  [id]             — Auto-generated by Dexie
 * @property {string}  name             — User-supplied label
 * @property {string}  instanceUrl      — Source Tacton instance URL
 * @property {string}  instanceName     — Source instance display name
 * @property {string}  ticketId         — Ticket ID it was captured from
 * @property {string}  ticketSummary    — Ticket display text
 * @property {string}  startingObject   — Root object type at capture time
 * @property {number}  capturedAt       — Unix timestamp (ms)
 * @property {number}  version          — Schema version (for forward compat)
 * @property {Object}  data             — The captured API data
 * @property {Array}   data.model       — fetchModel() result
 * @property {Object}  data.records     — { objectName: [...records] }
 * @property {Array}   data.bomRecords  — fetchBomRecords() result
 * @property {Array}   data.bomFields   — getBomFields() result
 * @property {Array}   data.bomSources  — getBomSources() result
 * @property {Object}  data.descriptions— { objectName: describeObject() result }
 * @property {Array}   data.configuredProducts — getConfiguredProductList() result
 * @property {Object}  data.cpData      — { cpId: fetchConfiguredProductData() result }
 * @property {Object}  data.cpAttributes— indexConfigAttributes() result
 * @property {Object}  [data.selectedObjects] — Which objects user chose to capture
 */

const CURRENT_VERSION = 1;

// ─── CRUD ───────────────────────────────────────────────────────────────

/** Get all offline packages, newest first. */
export async function getAllPackages() {
  const all = await db.offlinePackages.toArray();
  return all.sort((a, b) => (b.capturedAt || 0) - (a.capturedAt || 0));
}

/** Get a single package by ID. */
export async function getPackage(id) {
  return db.offlinePackages.get(id);
}

/** Save a new or updated package. Returns the saved package with ID. */
export async function savePackage(pkg) {
  const record = {
    ...pkg,
    version: pkg.version || CURRENT_VERSION,
    capturedAt: pkg.capturedAt || Date.now(),
  };
  if (record.id) {
    await db.offlinePackages.put(record);
    return record;
  }
  const id = await db.offlinePackages.add(record);
  return { ...record, id };
}

/** Delete a package by ID. */
export async function deletePackage(id) {
  await db.offlinePackages.delete(id);
}

// ─── Export / Import ────────────────────────────────────────────────────

/**
 * Export a package as a downloadable JSON file.
 * Strips the DB id so it can be imported as a new record.
 */
export function exportPackageAsJson(pkg) {
  const exportData = { ...pkg };
  delete exportData.id; // strip DB id for portability
  exportData._exportedAt = Date.now();
  exportData._format = 'tacton-docgen-offline';
  exportData._version = CURRENT_VERSION;

  const json = JSON.stringify(exportData, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  const safeName = (pkg.name || 'offline-package').replace(/[^a-zA-Z0-9_-]/g, '_');
  a.download = `${safeName}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Import a package from a JSON file (File object from <input type="file">).
 * Returns the saved package with new DB id.
 */
export async function importPackageFromFile(file) {
  const text = await file.text();
  const data = JSON.parse(text);

  // Validate format
  if (data._format !== 'tacton-docgen-offline') {
    throw new Error('Invalid file format — not a DocGen offline package.');
  }

  // Clean import metadata
  delete data.id;
  delete data._exportedAt;
  delete data._format;
  delete data._version;

  // Save as new package
  return savePackage(data);
}

/**
 * Import from raw JSON string (for programmatic use).
 */
export async function importPackageFromJson(jsonString) {
  const data = JSON.parse(jsonString);
  if (data._format !== 'tacton-docgen-offline') {
    throw new Error('Invalid format — not a DocGen offline package.');
  }
  delete data.id;
  delete data._exportedAt;
  delete data._format;
  delete data._version;
  return savePackage(data);
}

// ─── Helpers ────────────────────────────────────────────────────────────

/** Get a human-readable size estimate for a package. */
export function estimatePackageSize(pkg) {
  const json = JSON.stringify(pkg.data || {});
  const bytes = new Blob([json]).size;
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/** Count total records across all captured object types. */
export function countRecords(pkg) {
  const data = pkg.data || {};
  let total = 0;
  if (data.records) {
    for (const recs of Object.values(data.records)) {
      total += Array.isArray(recs) ? recs.length : 0;
    }
  }
  if (data.bomRecords) total += data.bomRecords.length;
  return total;
}

/** Generate a default package name. */
export function generatePackageName(instanceName, ticketId) {
  const date = new Date().toISOString().slice(0, 10);
  const inst = instanceName || 'Unknown';
  const ticket = ticketId || 'no-ticket';
  return `${inst} — ${ticket} — ${date}`;
}
